export const validatorMessages = {
  required: "Campo obligatorio",
  objectId: "El identificador no es válido.",
  invalidType: "Tipo de dato inválido",
  tooSmall: "El valor es demasiado pequeño",
  tooBig: "El valor es demasiado grande",
  invalidString: "Formato de texto inválido",
  invalidFormat: "Formato inválido",
  invalidEnumValue: "Valor no permitido",
  invalidValue: "Valor no permitido",
  invalidLiteral: "Valor no permitido",
  unrecognizedKeys: "Campos no permitidos",
  invalidUnion: "No coincide con ningún formato permitido",
  invalidDate: "Fecha inválida",
  notFinite: "El número no es válido",
  notMultipleOf: "El número no cumple con el múltiplo requerido",
  integer: "El número debe ser entero",
  notNegative: "El valor no puede ser negativo",
  custom: "No cumple con la validación requerida",
  validationError: "Error de validación",
  unexpected: "Ocurrió un error inesperado.",
  min: (value: number) => `El valor debe ser mayor o igual a ${value}`,
  max: (value: number) => `El valor debe ser menor o igual a ${value}`,
  minLength: (value: number) => `Debe tener al menos ${value} caracteres`,
  maxLength: (value: number) => `Debe tener como máximo ${value} caracteres`,
} as const;
